"use client"

import React from 'react';
import "globals.css";
import SearchBar from '../components/search_bar';
import Link from 'next/link';
import Image from 'next/image'

export default function Home({ suggestedBooks }) {
    return (
        <main>
            <div className="w-full h-screen bg-gradient-to-br from-[#F2D8B9] to-[#F0EFE2] flex flex-col text-center justify-center items-center m-auto gap-12">
                <h1 className='text-7xl font-bold w-1/2 text-[#333333]'>Get your book summary and key ideas generated by AI.</h1>
                <SearchBar className="w-[40%]" />
                <Link href={'book/the-miracle-morning'}>
                    <div>
                        <h3 className='text-xl font-semibold mb-2'>Or you can start with one of these</h3>
                        <ul className='flex gap-12'>
                            {
                                suggestedBooks.map((book) =>
                                    <li className='max-w-[150px] hover:scale-105 ease-in duration-100'>
                                        <div className={`bg-gray-50 p-2 rounded-lg shadow-xl`}>
                                            <Image src={"https:" + book.featuredImage.file.url} width="150" height="0" alt="Picture of the book cover" />
                                        </div>
                                    </li>
                                )
                            }
                        </ul>
                    </div>
                </Link>
            </div>
        </main>
    )
}

/* 
main e7e7e9
accent 158582
complement F4E6CB
auxiliary 373738
*/