"use client"

import React from 'react';
import "../globals.css";
import SearchBar from '../components/search_bar';
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

export default function Home() {
  return (
    <main>
      <div className="w-full h-screen bg-amber-300 flex flex-col text-center justify-center items-center m-auto gap-12">
        <h1 className='text-6xl font-bold w-1/2'>Get your book summary and key ideas generated by AI.</h1>
        <SearchBar />
        <div className='bg-red-500 w-[30rem] h-[20rem]'>Carrousel</div>
      </div>
    </main>
  )
}
