"use client"

import React from 'react';
import "../globals.css";
import SearchBar from '../components/search_bar';
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import Link from 'next/link';

export default function Home() {
  return (
    <main>
      <div className="w-full h-screen bg-[#e7e7e9] flex flex-col text-center justify-center items-center m-auto gap-12">
        <h1 className='text-7xl font-bold w-1/2 text-emerald-500'>Get your book summary and key ideas generated by AI.</h1>
        <SearchBar />
        <Link href={'book/the-miracle-morning'}>
          <div className='bg-red-500 w-[30rem] h-[20rem]'>Carrousel</div>
        </Link>
      </div>
    </main>
  )
}
